[build]
builder = "NIXPACKS"

[build.buildCommand]
cmd = "npm install && npm run build && chmod +x setup-database.sh && ./setup-database.sh"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"